### ISSUE TITLE
Publishing Tasks Checklist

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-spring-boot#24]
Publishing Tasks
- [x] Create a PR from `dev` to `master` branch
- [x] Create `qa` branch from `master` branch
- [x] Rename the guide repo
- [x] Refresh `qa` staging site and verify 
- [x] If qa site has no problem, request to refresh openliberty.io site
- [x] For `master` branch, add a tag by creating a new release for this repo with name "1st-release"
