### ISSUE TITLE
Post-Publishing Tests Checklist

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-spring-boot#25]
Post-Publishing Tests
- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on openliberty.io
- [x] Clone repo and test finish directory with no error

Other post-publishing tasks (to be done by the Admin Team)
- [x] Add description for the repo with link to guide's published website
- [x] Double check the SEO title and description are added for the guide
- [x] Create the Home and Branches wiki pages
- [x] Ensure automated test for PR and Continuous Tests are enabled for both `master` and `qa` branches and are run on Travis, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides) 
- [x] Ensure the automated tests are running successfully for the daily builds
- [x] Ensure the automated tests are running successfully for the daily docker image, if the guide uses a docker image
- [x] Enable pull creation notification on the repo for `was-lib-guides-alerts`, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#subscribing-static-guides-repositories-to-a-slack-channel)
- [x] Enable `master` and `qa` branches lock down, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides) 
    -  make sure the Branch protection rules were created
- [x] Add the new guide's repo to the `OpenLiberty/guides-common` ZenHub board
- [x] Delete `dev` branch
- [ ] (Optional) Send announcement to slack channel(s)
- [x] Arrange a demo at the EOI meeting
